add gh workflow for building example apps
fermyon/spin-rust-sdk pull request #37
Opened 2024-10-30 13:11 UTC by michelleN

Generated using @ThorstenHans spin gh plugin https://github.com/ThorstenHans/spin-gh-plugin 🚀 

`pin gh create-action` in the root dir discovers all the spin example app directories and generates the CI file here. I had to tweak a few things like deleting the unnecessary plugins, updating the yaml file name, workflow name, job name but I believe all of these things are configurable via the plugin flags. The next step here would be to ensure that no new example directories get missed and are easily added to the workflow file. Don't have a great story for that just yet but I figure this is a good start.

2024-10-30 13:30 UTC, lann commented
Assuming this is just building every example, I wonder if it would be better to have a `build-examples.sh` (with a e.g. `for example_dir in examples/* ...`) and just call that from the action?

2024-10-30 15:20 UTC, michelleN commented
@lann that definitely takes care of not having to add new examples to the workflow.  At first, I was thinking this setup is nice because can use `act` to run the workflow/build the examples locally which it does in a docker container so you don't have to fumble inconsistent rust/spin environments. If ever something is failing in CI, this setup may make it slightly easier to debug. However, you could have the same exact workflow with a build examples script and the build examples script might even be better if you actually do want to test with your local environment

The only other reason to go this route would be that the github actions output is easy to read and follow (see screenshot below). I can do my best with making the build script pretty though.
<img width="684" alt="Screenshot 2024-10-30 at 11 02 52 AM" src="https://github.com/user-attachments/assets/4f802a6c-6bfc-4560-8d38-b880611f2ecc">

2024-11-04 09:25 UTC, rylev requested changes
I'd also much prefer using a bash loop (either in a separate script or inline in the action) to loop over all examples. I think it's more important that need examples be automatically added than it is to have great output.

2024-11-04 14:42 UTC, lann commented
Oop sorry I missed your comment @michelleN. It is quite easy to group logs from bash by just printing some magic strings to stdout: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#grouping-log-lines

e.g.
```bash
for $dir in examples/*; do
  echo "::group::Building $dir"
  ...
  echo "::endgroup::"
done
```

2024-11-06 14:39 UTC, michelleN commented
sounds good. I'll update and open a new PR

2024-11-06 14:40 UTC, closed without merging